# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Osteria Nascostallavista"
description: > # this means to ignore newlines until "email:"
   Una Osteria vecchio stile, piatti deliziosi della tradizione. Se vuoi trovarci fruga fra le ricette.

email: a-mail@mail.mail
#blog logo
#logo: "/assets/images/onav.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/pots.jpg"

name: 'Ranulfo Dazzi'
author: 'Ranulfo'
author_image: "/assets/images/author.jpg"

paginate:	5

#url: "http://myblog.***.***" # the base hostname & protocol for your site
url: "http://www.osterianascostallavista.it" # the base hostname & protocol for your site
#baseurl: "/osteria_nascosta"
baseurl: ""
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social: